version: '3'
services:
  mynginx:
    image: nginxinc/nginx-unprivileged
    container_name: mynginx
    networks:
      - cesnet1

    volumes:
      - /vagrant/containers/reverse-proxy-ipv6/default.conf:/etc/nginx/conf.d/default.conf
      - /vagrant/containers/reverse-proxy-ipv6/certificate:/certificate
    ports:
      - ":::443:443"
    extra_hosts:
     - "host.docker.internal:host-gateway"

networks:
  cesnet1:
    external: true
