version: '3'
services:
  nodered:
    image: nginxinc/nginx-unprivileged
    container_name: mynginx
    volumes:
      - /home/sklein/IdeaProjects/reverse-proxy-ipv6/default.conf:/etc/nginx/conf.d/default.conf
      - /home/sklein/IdeaProjects/reverse-proxy-ipv6/volumes/certificate:/certificate
    ports:
      - "fde4:8dba:82e1::c4:80:8081"
